// Product specifications can be made here
export default {
  products: [
    {
      _id: "1",
      name: "Haj Benjamin Masked",
      image: "/images/Pal2.png",
      category: "Hoodie",
      collectionName: "Benjamins Collection",
      price: "50",
      countInStock: 0,
    },
    {
      _id: "2",
      name: "Haj Benjamin Bearded",
      image: "/images/Pal3.png",
      category: "Hoodie",
      collectionName: "Benjamins Collection",
      price: "50",
      countInStock: 10,
    },
    {
      _id: "3",
      name: "Haj Benjamin French Kissed",
      image: "/images/Pal4.png",
      category: "Hoodie",
      collectionName: "Benjamins Collection",
      price: "50",
      countInStock: 10,
    },
    {
      _id: "4",
      name: "Haj Benjamin Masked",
      image: "/images/Jor2.jpg",
      category: "Hoodie",
      collectionName: "Benjamins Collection",
      price: "50",
      countInStock: 10,
    },
    {
      _id: "5",
      name: "Haj Benjamin Bearded",
      image: "/images/Jor3.jpg",
      category: "Hoodie",
      collectionName: "Benjamins Collection",
      price: "50",
      countInStock: 10,
    },
    {
      _id: "6",
      name: "Haj Benjamin French Kissed",
      image: "/images/Jor4.jpg",
      category: "Hoodie",
      collectionName: "Benjamins Collection",
      price: "50",
      countInStock: 10,
    },
  ],
};
